version: "3.8"

services:
  balance-service:
    build:
      context: ./apps/balance-service
    container_name: balance-service
    ports:
      - "${BALANCE_SERVER_PORT}:${BALANCE_SERVER_PORT}" 
    environment:
      - NODE_ENV=development
      - SERVER_PORT=${BALANCE_SERVER_PORT}
      - RATE_SERVER_URL=${RATE_SERVER_URL}
    volumes:
      - ./libs/shared:/usr/src/app/libs/shared 
      - ./apps/balance-service/data:/usr/src/app/data 
    networks:
      - crypto-network

  rate-service:
    build:
      context: ./apps/rate-service
    container_name: rate-service
    ports:
      - "${RATE_SERVER_PORT}:${RATE_SERVER_PORT}"
    environment:
      - NODE_ENV=development 
      - SERVER_PORT=${RATE_SERVER_PORT}
      - RATE_REFRESH_INTERVAL=${RATE_REFRESH_INTERVAL}
    volumes:
      - ./libs/shared:/usr/src/app/libs/shared 
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
