version: "3.8"

services:
  balance-service:
    build:
      context: ./apps/balance-service
    container_name: balance-service
    ports:
      - "${BALANCE_SERVER_PORT}:${BALANCE_SERVER_PORT}"
    environment:
      - NODE_ENV=development
    volumes:
      - ./libs/shared:/usr/src/app/libs/shared 
      - ./apps/balance-service/data:/usr/src/app/data 
      - ./testUtils:/usr/testUtils 
    networks:
      - crypto-network

  rate-service:
    build:
      context: ./apps/rate-service
    container_name: rate-service
    ports:
      - "${RATE_SERVER_PORT}:${RATE_SERVER_PORT}"
    environment:
      - NODE_ENV=development 
    volumes:
      - ./libs/shared:/usr/src/app/libs/shared 
      - ./testUtils:/usr/testUtils 
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
